from enum import Enum

# Header
HEADER_SIZE = 7
CLIENT_ID_SIZE = 16
VERSION_SIZE = 1
CODE_SIZE = 2
PAYLOAD_SIZE = 4
# AUTH & MSG PAYLOAD
NAME_SIZE_SIZE = 255
PASSWORD_SIZE = 255
SYMMETRIC_KEY_SIZE = 32
SERVER_ID_SIZE = 16
NONCE_SIZE = 8
ENCRYPTED_NONCE_SIZE = 16
# Encrypted Key
IV_SIZE = 16
AES_KEY_SIZE = 32
# TICKET
CREATION_TIME_SIZE = 8
EXPIRATION_TIME_SIZE = 8
TICKET_PADDING_SIZE = 8
TICKET_SIZE = VERSION_SIZE + CLIENT_ID_SIZE + SERVER_ID_SIZE + CREATION_TIME_SIZE + IV_SIZE + AES_KEY_SIZE\
              + EXPIRATION_TIME_SIZE + TICKET_PADDING_SIZE  # 97 + 8(padding)

PROTOCOL_VERSION = 24


# Request Codes
class ERequestCode(Enum):
    REQUEST_CLIENT_REGISTRATION = 1024
    REQUEST_SERVER_REGISTRATION = 1025
    REQUEST_MESSAGE_SERVERS_LIST = 1026
    REQUEST_SYMMETRIC_KEY = 1027


# Responses Codes
class EResponseCode(Enum):
    RESPONSE_REGISTRATION_OK = 1600
    RESPONSE_REGISTRATION_ERROR = 1601
    RESPONSE_MESSAGE_SERVERS_LIST = 1602
    RESPONSE_SYMMETRIC_KEY = 1603


# Request Codes
class ERequestCodeMsgService(Enum):
    REQUEST_SYMMETRIC_KEY = 1028
    REQUEST_SEND_MESSAGE = 1029


# Responses Codes
class EResponseCodeMsgService(Enum):
    RESPONSE_RECEIVE_KEY_OK = 1604
    RESPONSE_RECEIVE_MESSAGE_OK = 1605
    RESPONSE_SERVER_ERROR = 1609


